import type { FlagDefinition } from './flag-types.ts';

export const CONNECTION_FLAG_DEFINITIONS: readonly FlagDefinition[] = [
  {
    key: 'config',
    names: ['--config'],
    type: 'string',
    usageLabel: '--config <path>',
    usageDescription: 'Load CLI defaults from a specific config file',
  },
  {
    key: 'remoteConfig',
    names: ['--remote-config'],
    type: 'string',
    usageLabel: '--remote-config <path>',
    usageDescription: 'Load remote host + Metro workflow settings from a specific profile file',
  },
  {
    key: 'stateDir',
    names: ['--state-dir'],
    type: 'string',
    usageLabel: '--state-dir <path>',
    usageDescription:
      'Daemon state directory (defaults to ~/.agent-device for packages, or a worktree-scoped dev dir from source)',
  },
  {
    key: 'daemonBaseUrl',
    names: ['--daemon-base-url'],
    type: 'string',
    usageLabel: '--daemon-base-url <url>',
    usageDescription: 'Explicit remote HTTP daemon base URL (skip local daemon discovery/startup)',
  },
  {
    key: 'daemonAuthToken',
    names: ['--daemon-auth-token'],
    type: 'string',
    usageLabel: '--daemon-auth-token <token>',
    usageDescription:
      'Remote HTTP daemon or proxy auth token (sent as request token and bearer header)',
  },
  {
    key: 'daemonTransport',
    names: ['--daemon-transport'],
    type: 'enum',
    enumValues: ['auto', 'socket', 'http'],
    usageLabel: '--daemon-transport auto|socket|http',
    usageDescription: 'Daemon client transport preference',
  },
  {
    key: 'daemonServerMode',
    names: ['--daemon-server-mode'],
    type: 'enum',
    enumValues: ['socket', 'http', 'dual'],
    usageLabel: '--daemon-server-mode socket|http|dual',
    usageDescription: 'Daemon server mode used when spawning daemon',
  },
  {
    key: 'proxyHost',
    names: ['--host'],
    type: 'string',
    usageLabel: '--host <host>',
    usageDescription: 'Proxy: host interface to bind (default: 127.0.0.1)',
  },
  {
    key: 'proxyPort',
    names: ['--port'],
    type: 'int',
    min: 1,
    max: 65535,
    usageLabel: '--port <port>',
    usageDescription: 'Proxy: TCP port to bind (default: 0, choose a free port)',
  },
  {
    key: 'tenant',
    names: ['--tenant'],
    type: 'string',
    usageLabel: '--tenant <id>',
    usageDescription: 'Tenant scope identifier for isolated daemon sessions',
  },
  {
    key: 'sessionIsolation',
    names: ['--session-isolation'],
    type: 'enum',
    enumValues: ['none', 'tenant'],
    usageLabel: '--session-isolation none|tenant',
    usageDescription: 'Session isolation strategy (tenant prefixes session namespace)',
  },
  {
    key: 'runId',
    names: ['--run-id'],
    type: 'string',
    usageLabel: '--run-id <id>',
    usageDescription: 'Run identifier used for tenant lease admission checks',
  },
  {
    key: 'leaseId',
    names: ['--lease-id'],
    type: 'string',
    usageLabel: '--lease-id <id>',
    usageDescription: 'Lease identifier bound to tenant/run admission scope',
  },
  {
    key: 'leaseBackend',
    names: ['--lease-backend'],
    type: 'enum',
    enumValues: ['ios-simulator', 'ios-instance', 'android-instance'],
    usageLabel: '--lease-backend ios-simulator|ios-instance|android-instance',
    usageDescription: 'Lease backend for remote tenant connection admission',
  },
  {
    key: 'provider',
    names: ['--provider'],
    type: 'string',
    usageLabel: '--provider <name>',
    usageDescription: 'Cloud provider name for provider-scoped commands',
  },
  {
    key: 'providerSessionId',
    names: ['--provider-session'],
    type: 'string',
    usageLabel: '--provider-session <id>',
    usageDescription: 'Cloud provider session id or ARN',
  },
  {
    key: 'providerApp',
    names: ['--provider-app'],
    type: 'string',
    usageLabel: '--provider-app <ref-or-path>',
    usageDescription:
      'Cloud provider app reference or local app path used when creating hosted WebDriver sessions',
  },
  {
    key: 'providerOsVersion',
    names: ['--provider-os-version', '--os-version'],
    type: 'string',
    usageLabel: '--provider-os-version <version>',
    usageDescription: 'Hosted cloud provider OS version, for example 17 or 14.0',
  },
  {
    key: 'providerProject',
    names: ['--provider-project'],
    type: 'string',
    usageLabel: '--provider-project <name>',
    usageDescription: 'Hosted cloud provider project label',
  },
  {
    key: 'providerBuild',
    names: ['--provider-build'],
    type: 'string',
    usageLabel: '--provider-build <name>',
    usageDescription: 'Hosted cloud provider build label',
  },
  {
    key: 'providerSessionName',
    names: ['--provider-session-name'],
    type: 'string',
    usageLabel: '--provider-session-name <name>',
    usageDescription: 'Hosted cloud provider session label',
  },
  {
    key: 'awsProjectArn',
    names: ['--aws-project-arn'],
    type: 'string',
    usageLabel: '--aws-project-arn <arn>',
    usageDescription: 'AWS Device Farm project ARN for hosted WebDriver sessions',
  },
  {
    key: 'awsDeviceArn',
    names: ['--aws-device-arn'],
    type: 'string',
    usageLabel: '--aws-device-arn <arn>',
    usageDescription: 'AWS Device Farm device ARN for hosted WebDriver sessions',
  },
  {
    key: 'awsAppArn',
    names: ['--aws-app-arn'],
    type: 'string',
    usageLabel: '--aws-app-arn <arn>',
    usageDescription: 'AWS Device Farm app ARN attached to hosted remote access sessions',
  },
  {
    key: 'awsRegion',
    names: ['--aws-region'],
    type: 'string',
    usageLabel: '--aws-region <region>',
    usageDescription: 'AWS region for Device Farm API calls',
  },
  {
    key: 'awsInteractionMode',
    names: ['--aws-interaction-mode'],
    type: 'enum',
    enumValues: ['INTERACTIVE', 'NO_VIDEO', 'VIDEO_ONLY'],
    usageLabel: '--aws-interaction-mode INTERACTIVE|NO_VIDEO|VIDEO_ONLY',
    usageDescription: 'AWS Device Farm remote access interaction mode',
  },
  {
    key: 'force',
    names: ['--force'],
    type: 'boolean',
    usageLabel: '--force',
    usageDescription: 'Force connection state replacement when reconnecting',
  },
  {
    key: 'noLogin',
    names: ['--no-login'],
    type: 'boolean',
    usageLabel: '--no-login',
    usageDescription: 'Connect: fail instead of starting implicit cloud login',
  },
  {
    key: 'sessionLock',
    names: ['--session-lock'],
    type: 'enum',
    enumValues: ['reject', 'strip'],
    usageLabel: '--session-lock reject|strip',
    usageDescription:
      'Lock bound-session device routing for this CLI invocation and nested batch steps',
  },
  {
    key: 'sessionLocked',
    names: ['--session-locked'],
    type: 'boolean',
    usageLabel: '--session-locked',
    usageDescription: 'Deprecated alias for --session-lock reject',
  },
  {
    key: 'sessionLockConflicts',
    names: ['--session-lock-conflicts'],
    type: 'enum',
    enumValues: ['reject', 'strip'],
    usageLabel: '--session-lock-conflicts reject|strip',
    usageDescription: 'Deprecated alias for --session-lock',
  },
];
