import { SESSION_SURFACES } from '../../contracts/session-surface.ts';
import { PLATFORM_SELECTORS } from '../../kernel/device.ts';
import { PERF_KIND_VALUES } from '../../contracts/perf.ts';
import type { FlagDefinition } from './flag-types.ts';

export const TARGET_FLAG_DEFINITIONS: readonly FlagDefinition[] = [
  {
    key: 'platform',
    names: ['--platform'],
    type: 'enum',
    enumValues: PLATFORM_SELECTORS,
    usageLabel: `--platform ${PLATFORM_SELECTORS.join('|')}`,
    usageDescription: 'Platform to target (`apple` aliases the Apple automation backend)',
  },
  {
    key: 'target',
    names: ['--target'],
    type: 'enum',
    enumValues: ['mobile', 'tv', 'desktop'],
    usageLabel: '--target mobile|tv|desktop',
    usageDescription: 'Device target class to match',
  },
  {
    key: 'device',
    names: ['--device'],
    type: 'string',
    usageLabel: '--device <name>',
    usageDescription: 'Device name to target',
  },
  {
    key: 'udid',
    names: ['--udid'],
    type: 'string',
    usageLabel: '--udid <udid>',
    usageDescription: 'iOS device UDID',
  },
  {
    key: 'serial',
    names: ['--serial'],
    type: 'string',
    usageLabel: '--serial <serial>',
    usageDescription: 'Android device serial',
  },
  {
    key: 'surface',
    names: ['--surface'],
    type: 'enum',
    enumValues: SESSION_SURFACES,
    usageLabel: '--surface app|frontmost-app|desktop|menubar',
    usageDescription: 'macOS session surface for open (defaults to app)',
  },
  {
    key: 'headless',
    names: ['--headless'],
    type: 'boolean',
    usageLabel: '--headless',
    usageDescription: 'Boot: launch Android emulator without a GUI window',
  },
  {
    key: 'targetApp',
    names: ['--app', '--target-app'],
    type: 'string',
    usageLabel: '--app <id-or-name>',
    usageDescription: 'Doctor: verify an installed target app without opening a session',
  },
  {
    key: 'metroHost',
    names: ['--metro-host'],
    type: 'string',
    usageLabel: '--metro-host <host>',
    usageDescription: 'Session-scoped Metro/debug host hint',
  },
  {
    key: 'metroPort',
    names: ['--metro-port'],
    type: 'int',
    min: 1,
    max: 65535,
    usageLabel: '--metro-port <port>',
    usageDescription:
      'Session-scoped Metro/debug port hint; on an emulator/simulator the host defaults to the loopback alias, physical devices still need --metro-host',
  },
  {
    key: 'metroProjectRoot',
    names: ['--project-root'],
    type: 'string',
    usageLabel: '--project-root <path>',
    usageDescription: 'metro prepare: React Native project root (default: cwd)',
  },
  {
    key: 'kind',
    names: ['--kind'],
    type: 'enum',
    enumValues: ['auto', 'react-native', 'expo', 'repack', ...PERF_KIND_VALUES],
    usageLabel: '--kind <kind>',
    usageDescription:
      'Kind selector for commands that support it, such as metro prepare or perf artifact collectors',
  },
  {
    key: 'perfTemplate',
    names: ['--template'],
    type: 'string',
    usageLabel: '--template <name>',
    usageDescription: 'Perf xctrace template name, for example Time Profiler',
  },
  {
    key: 'metroKind',
    names: ['--metro-kind'],
    type: 'enum',
    enumValues: ['auto', 'react-native', 'expo', 'repack'],
    usageLabel: '--metro-kind auto|react-native|expo|repack',
    usageDescription: 'metro prepare: detect or force the React Native dev-server launcher kind',
  },
  {
    key: 'metroPublicBaseUrl',
    names: ['--public-base-url'],
    type: 'string',
    usageLabel: '--public-base-url <url>',
    usageDescription: 'metro prepare: public base URL used for direct dev-server bundle hints',
  },
  {
    key: 'metroProxyBaseUrl',
    names: ['--proxy-base-url'],
    type: 'string',
    usageLabel: '--proxy-base-url <url>',
    usageDescription: 'metro prepare: optional bridge origin for remote dev-server access',
  },
  {
    key: 'metroBearerToken',
    names: ['--bearer-token'],
    type: 'string',
    usageLabel: '--bearer-token <token>',
    usageDescription:
      'metro prepare: host bridge bearer token (or AGENT_DEVICE_METRO_BEARER_TOKEN; falls back to AGENT_DEVICE_DAEMON_AUTH_TOKEN)',
  },
  {
    key: 'metroPreparePort',
    names: ['--port'],
    type: 'int',
    min: 1,
    max: 65535,
    usageLabel: '--port <port>',
    usageDescription: 'metro prepare: local dev-server port (default: 8081)',
  },
  {
    key: 'metroListenHost',
    names: ['--listen-host'],
    type: 'string',
    usageLabel: '--listen-host <host>',
    usageDescription: 'metro prepare: host dev server listens on (default: 0.0.0.0)',
  },
  {
    key: 'metroStatusHost',
    names: ['--status-host'],
    type: 'string',
    usageLabel: '--status-host <host>',
    usageDescription:
      'metro prepare: host used for local dev-server /status polling (default: 127.0.0.1)',
  },
  {
    key: 'metroStartupTimeoutMs',
    names: ['--startup-timeout-ms'],
    type: 'int',
    min: 1,
    usageLabel: '--startup-timeout-ms <ms>',
    usageDescription: 'metro prepare: timeout while waiting for the dev server to become ready',
  },
  {
    key: 'metroProbeTimeoutMs',
    names: ['--probe-timeout-ms'],
    type: 'int',
    min: 1,
    usageLabel: '--probe-timeout-ms <ms>',
    usageDescription: 'metro prepare: timeout for /status and proxy bridge calls',
  },
  {
    key: 'metroRuntimeFile',
    names: ['--runtime-file'],
    type: 'string',
    usageLabel: '--runtime-file <path>',
    usageDescription: 'metro prepare: optional file path to persist the JSON result',
  },
  {
    key: 'metroNoReuseExisting',
    names: ['--no-reuse-existing'],
    type: 'boolean',
    usageLabel: '--no-reuse-existing',
    usageDescription: 'metro prepare: always start a fresh Metro process',
  },
  {
    key: 'metroNoInstallDeps',
    names: ['--no-install-deps'],
    type: 'boolean',
    usageLabel: '--no-install-deps',
    usageDescription: 'metro prepare: skip package-manager install when node_modules is missing',
  },
  {
    key: 'bundleUrl',
    names: ['--bundle-url'],
    type: 'string',
    usageLabel: '--bundle-url <url>',
    usageDescription: 'Session-scoped bundle URL hint',
  },
  {
    key: 'launchUrl',
    names: ['--launch-url'],
    type: 'string',
    usageLabel: '--launch-url <url>',
    usageDescription: 'Session-scoped deep link / launch URL hint',
  },
  {
    key: 'iosSimulatorDeviceSet',
    names: ['--ios-simulator-device-set'],
    type: 'string',
    usageLabel: '--ios-simulator-device-set <path>',
    usageDescription: 'Scope iOS simulator discovery/commands to this simulator device set',
  },
  {
    key: 'iosXctestrunFile',
    names: ['--ios-xctestrun-file'],
    type: 'string',
    usageLabel: '--ios-xctestrun-file <path>',
    usageDescription: 'Use an externally built iOS XCTest runner .xctestrun artifact',
  },
  {
    key: 'iosXctestDerivedDataPath',
    names: ['--ios-xctest-derived-data-path'],
    type: 'string',
    usageLabel: '--ios-xctest-derived-data-path <path>',
    usageDescription: 'Derived data path for external iOS XCTest runner execution',
  },
  {
    key: 'iosXctestEnvDir',
    names: ['--ios-xctest-env-dir'],
    type: 'string',
    usageLabel: '--ios-xctest-env-dir <path>',
    usageDescription: 'Writable directory for per-session iOS XCTest runner env overlays',
  },
  {
    key: 'deviceHub',
    names: ['--device-hub'],
    type: 'boolean',
    usageLabel: '--device-hub',
    usageDescription: 'open: use Xcode Device Hub when surfacing Apple simulators',
  },
  {
    key: 'testIme',
    names: ['--test-ime'],
    type: 'boolean',
    usageLabel: '--test-ime',
    usageDescription:
      'open: activate the headless Android test IME for deterministic Unicode text entry (default on for emulators; opt-in on real devices)',
  },
  {
    key: 'testIme',
    names: ['--no-test-ime'],
    type: 'boolean',
    setValue: false,
    usageLabel: '--no-test-ime',
    usageDescription:
      'open: keep the real Android keyboard even on emulators (opt out of the headless test IME)',
  },
  {
    key: 'androidDeviceAllowlist',
    names: ['--android-device-allowlist'],
    type: 'string',
    usageLabel: '--android-device-allowlist <serials>',
    usageDescription: 'Comma/space separated Android serial allowlist for discovery/selection',
  },
  {
    key: 'remote',
    names: ['--remote'],
    type: 'boolean',
    usageLabel: '--remote',
    usageDescription: 'Doctor: check remote connection setup instead of local device inventory',
  },
  {
    key: 'activity',
    names: ['--activity'],
    type: 'string',
    usageLabel: '--activity <component>',
    usageDescription: 'Android app launch activity (package/Activity); not for URL opens',
  },
  {
    key: 'launchConsole',
    names: ['--launch-console'],
    type: 'string',
    usageLabel: '--launch-console <path>',
    usageDescription: 'open: capture the initial iOS simulator launch console window to a file',
  },
  {
    key: 'launchArgs',
    names: ['--launch-args'],
    type: 'string',
    multiple: true,
    usageLabel: '--launch-args <arg>',
    usageDescription:
      'open: repeatable launch argument forwarded verbatim to the platform launch command (iOS app process args; Android adb shell am start args). Linux and macOS reject the flag.',
  },
  {
    key: 'header',
    names: ['--header'],
    type: 'string',
    multiple: true,
    usageLabel: '--header <name:value>',
    usageDescription: 'install-from-source: repeatable HTTP header for URL downloads',
  },
  {
    key: 'githubActionsArtifact',
    names: ['--github-actions-artifact'],
    type: 'string',
    usageLabel: '--github-actions-artifact <owner/repo:artifact>',
    usageDescription: 'install-from-source: GitHub Actions artifact resolved by a remote daemon',
  },
  {
    key: 'installSource',
    // Config-only virtual option; parsed explicitly from JSON before generic string options.
    names: [],
    type: 'string',
  },
  {
    key: 'session',
    names: ['--session'],
    type: 'string',
    usageLabel: '--session <name>',
    usageDescription: 'Named session',
  },
];
