package dev.agentdevice.conformance

import com.fasterxml.jackson.databind.node.ObjectNode
import maestro.orchestra.yaml.YamlCommandReader
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.createTempDirectory

/**
 * Layer 2 — semantic vectors generated by the JVM harness.
 *
 * Two kinds of vector, both read from the pinned artifacts (never transcribed):
 *  - `constants`: `static final` values read straight out of the bytecode via
 *    ASM (no class initialization), e.g. the retry cap and animation-wait
 *    thresholds.
 *  - `modelDefaults`: fields defaulted by the upstream parser, observed by
 *    parsing a minimal inline flow and reading the value back off the command
 *    model (e.g. the 400ms default swipe duration).
 *
 * The Node verifier cross-checks each vector against the corresponding
 * agent-device engine constant, or records it as a documented reference value
 * (for intentionally divergent upstream constants such as the iOS pre-tap gate).
 */
fun emitLayer2(): ObjectNode {
    val root = fixtureMapper.createObjectNode()
    root.put("layer", 2)
    root.put("description", "Upstream Maestro semantic vectors. Generated by the JVM harness; do not hand-edit.")

    val constants = root.putArray("constants")
    for (c in CONSTANT_VECTORS) {
        val (owner, field) = c.symbol.split("#", limit = 2)
        val value = readConstant(owner.replace('.', '/'), field)
        val node = constants.addObject()
        node.put("id", c.id)
        node.put("symbol", c.symbol)
        node.put("note", c.note)
        putNumber(node, "value", value)
    }

    val modelDefaults = root.putArray("modelDefaults")
    for (d in MODEL_DEFAULT_VECTORS) {
        val value = d.read()
        val node = modelDefaults.addObject()
        node.put("id", d.id)
        node.put("flow", d.flow.trim())
        node.put("accessor", d.accessor)
        putNumber(node, "value", value)
    }
    return root
}

private data class ConstantVector(val id: String, val symbol: String, val note: String)

private val CONSTANT_VECTORS = listOf(
    ConstantVector(
        "retryMaxRetries",
        "maestro.orchestra.Orchestra#MAX_RETRIES_ALLOWED",
        "Upper bound Orchestra clamps a retry block's maxRetries to (coerceAtMost).",
    ),
    ConstantVector(
        "maxEraseCharacters",
        "maestro.orchestra.Orchestra#MAX_ERASE_CHARACTERS",
        "Upper bound on eraseText character count.",
    ),
    ConstantVector(
        "animationWaitThreshold",
        "maestro.Maestro#SCREENSHOT_DIFF_THRESHOLD",
        "Screenshot-diff threshold (romankh3 0-100 scale) for waitForAnimationToEnd stability.",
    ),
    ConstantVector(
        "animationWaitTimeoutMs",
        "maestro.Maestro#ANIMATION_TIMEOUT_MS",
        "Default waitForAnimationToEnd timeout.",
    ),
    ConstantVector(
        "iosScreenSettleTimeoutMs",
        "maestro.drivers.IOSDriver#SCREEN_SETTLE_TIMEOUT_MS",
        "Upstream iOS pre-tap static-screen gate; agent-device intentionally omits it (expected divergence).",
    ),
)

private class ModelDefaultVector(
    val id: String,
    val flow: String,
    val accessor: String,
    val read: () -> Any,
)

private val MODEL_DEFAULT_VECTORS = listOf(
    ModelDefaultVector(
        id = "swipeDurationMs",
        flow = "- swipe:\n    direction: LEFT\n",
        accessor = "SwipeCommand.duration",
        read = { parseSingle("- swipe:\n    direction: LEFT\n", "getSwipeCommand", "getDuration") },
    ),
)

/** Parse a one-command flow and read a numeric field off the active command. */
private fun parseSingle(flowBody: String, wrapperGetter: String, fieldGetter: String): Any {
    val dir = createTempDirectory("maestro-conformance-l2")
    try {
        val file = dir.resolve("flow.yaml")
        Files.writeString(file, "appId: com.example\n---\n$flowBody")
        val commands = YamlCommandReader.readCommands(file)
        for (command in commands) {
            val sub = command.javaClass.getMethod(wrapperGetter).invoke(command) ?: continue
            return sub.javaClass.getMethod(fieldGetter).invoke(sub)
                ?: error("$wrapperGetter.$fieldGetter returned null")
        }
        error("No $wrapperGetter command produced by flow")
    } finally {
        Files.walk(dir).sorted(Comparator.reverseOrder()).forEach(Files::delete)
    }
}

private fun putNumber(node: ObjectNode, key: String, value: Any) {
    when (value) {
        is Int -> node.put(key, value)
        is Long -> node.put(key, value)
        is Double -> node.put(key, value)
        is Float -> node.put(key, value.toDouble())
        else -> node.put(key, value.toString())
    }
}
