export const IOS_BOOT_TIMEOUT_MS = 180_000;

export const IOS_SIMCTL_LIST_TIMEOUT_MS = 60_000;

export const IOS_APP_LAUNCH_TIMEOUT_MS = 60_000;

export const IOS_DEVICECTL_TIMEOUT_MS = 20_000;

export const IOS_DEVICE_INSTALL_TIMEOUT_MS = 120_000;

export const IOS_SIMULATOR_FOCUS_TIMEOUT_MS = 10_000;

export const IOS_SIMULATOR_TERMINATE_TIMEOUT_MS = 15_000;

export const IOS_SIMULATOR_SCREENSHOT_TIMEOUT_MS = 20_000;

export const IOS_RUNNER_SCREENSHOT_COPY_TIMEOUT_MS = 20_000;

export const IOS_SIMULATOR_SCREENSHOT_RETRY_MAX_ATTEMPTS = 5;
export const IOS_SIMULATOR_SCREENSHOT_RETRY_BASE_DELAY_MS = 1_000;
export const IOS_SIMULATOR_SCREENSHOT_RETRY_MAX_DELAY_MS = 5_000;
