export { createAgentDeviceClient } from './client.ts';
export { createLocalArtifactAdapter } from './io.ts';
export { AppError, isAgentDeviceError, normalizeAgentDeviceError } from './kernel/errors.ts';
export { centerOfRect } from './kernel/snapshot.ts';

export type {
  ArtifactAdapter,
  ArtifactDescriptor,
  CreateTempFileOptions,
  FileInputRef,
  FileOutputRef,
  LocalArtifactAdapterOptions,
  OutputVisibility,
  ReserveOutputOptions,
  ReservedOutputFile,
  ResolveInputOptions,
  ResolvedInputFile,
  TemporaryFile,
} from './io.ts';

export type { AppErrorCode, NormalizedError } from './kernel/errors.ts';

export type {
  ReplayTestReporter,
  ReplayTestReporterContext,
  ReplayTestReporterFactory,
  ReplayTestReporterLoadContext,
} from './cli-test-reporters/types.ts';

export type { CommandResult } from './core/command-descriptor/command-result.ts';
export type { ResponseLevel } from './contracts.ts';
export type { BootCommandResult, ShutdownCommandResult } from './contracts/device.ts';
export type { ViewportCommandResult } from './contracts/viewport.ts';

export type {
  AgentDeviceClient,
  AgentDeviceClientConfig,
  AgentDeviceCommandClient,
  AgentDeviceDaemonTransport,
  AgentDeviceDevice,
  AgentDeviceIdentifiers,
  AgentDeviceRequestOverrides,
  AgentDeviceSelectionOptions,
  AgentDeviceSession,
  AgentDeviceSessionDevice,
  AlertAction,
  AlertCommandOptions,
  AlertInfo,
  AlertPlatform,
  AlertCommandResult,
  AlertSource,
  AppCloseOptions,
  AppCloseResult,
  AppDeployOptions,
  AppDeployResult,
  AppInstallFromSourceOptions,
  AppInstallFromSourceResult,
  AppListOptions,
  AppOpenOptions,
  AppOpenResult,
  AppPushOptions,
  AppStateCommandOptions,
  AppStateCommandResult,
  AppSwitcherCommandOptions,
  AppSwitcherCommandResult,
  AppTriggerEventOptions,
  BackCommandOptions,
  BackCommandResult,
  BatchRunResult,
  BatchRunOptions,
  BatchStep,
  CaptureDiffOptions,
  CaptureScreenshotOptions,
  CaptureScreenshotResult,
  CaptureSnapshotOptions,
  CaptureSnapshotResult,
  ClickOptions,
  ClipboardCommandOptions,
  ClipboardCommandResult,
  CommandRequestResult,
  DeviceBootOptions,
  DeviceShutdownOptions,
  ElementTarget,
  FillOptions,
  FindLocator,
  FindOptions,
  FocusOptions,
  GetOptions,
  HomeCommandOptions,
  HomeCommandResult,
  InteractionTarget,
  IsOptions,
  KeyboardCommandOptions,
  KeyboardCommandResult,
  LogsOptions,
  LongPressOptions,
  MaterializationReleaseOptions,
  MaterializationReleaseResult,
  MetroPrepareOptions,
  MetroPrepareResult,
  MetroReloadOptions,
  MetroReloadResult,
  NetworkOptions,
  PerfOptions,
  PermissionTarget,
  PinchOptions,
  PressOptions,
  RecordOptions,
  ReplayRunOptions,
  ReplayTestOptions,
  RotateCommandOptions,
  RotateCommandResult,
  ScrollOptions,
  SessionCloseResult,
  SettingsUpdateOptions,
  StartupPerfSample,
  SwipeOptions,
  TargetShutdownResult,
  TraceOptions,
  TypeTextOptions,
  WaitCommandOptions,
  WaitCommandResult,
} from './client.ts';

export type {
  Point,
  Rect,
  ScreenshotOverlayRef,
  SnapshotNode,
  SnapshotVisibility,
  SnapshotVisibilityReason,
} from './kernel/snapshot.ts';
